name: mayr_fake_api
description: >
  A pure Dart package that intercepts API calls and returns fake JSON responses from local files during development.
version: 2.0.0
homepage: https://github.com/MayR-Labs/mayr_dart_fake_api
repository: https://github.com/MayR-Labs/mayr_dart_fake_api
issue_tracker: https://github.com/MayR-Labs/mayr_dart_fake_api/issues
documentation: https://github.com/MayR-Labs/mayr_dart_fake_api/wiki
LICENSE: MIT

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.0.0
  path: ^1.8.0
  http: ^1.0.0
  uuid: ^4.0.0
  faker: ^2.2.0

dev_dependencies:
  test: ^1.24.0
  lints: ^5.0.0
  mockito: ^5.4.6

topics:
  - api
  - testing
  - dart
  - productivity
  - development
